name: Docker Build and Push

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 授予 GITHUB_TOKEN 写入 GHCR 的权限
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # 自动生成的 Token

      - name: Set repository name to lowercase
        run: echo "IMAGE_NAME_LC=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # 使用 commit hash 作为唯一的版本标签
          tags: ghcr.io/${{ env.IMAGE_NAME_LC }}:${{ github.sha }}
          # 同时打一个 "latest" 标签
          labels: "version=${{ github.sha }}"
